### PR TITLE
Travis-ci: added support for ppc64le build along with amd64

### PR DESCRIPTION
**Pull request by sanjay-cpu**
Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjay-cpu/dfdatetime/builds/186432263 . I believe it is ready for the final review and merge.
Please have a look on it and if everything looks fine for you then please approve it for merge.

Thanks !!

### CODE REVIEW

**Comment by joachimmetz** [comment]
@sanjay-cpu what is the reason for adding this?

**Review by joachimmetz — COMMENTED** [review]
@sanjay-cpu what is the reason for adding this? This is a Python project so the architecture tests do not provide any additional test coverage, also these architectures are not supported by the GIFT COPR/PPA.

**Comment by sanjay-cpu** [comment]
Hi @gerrith3 , Please look into this.

**Comment by joachimmetz** [comment]
@sanjay-cpu can you provide some context otherwise I'll ban you from this project as SPAM.

**Comment by gerrith3** [comment]
Hey sorry @joachimmetz - the reason for adding this is that it is a part of the Debian/Ubuntu releases for ppc64le, and while python projects usually run without change on Power, it turns out that something like 30% or so fail because they build in dependencies on Intel binaries.  This is a simple regression early  catch things early, rather than trying to catch them during integration into a distro, or even when someone pulls this project for any local use.  Our team has had to port hundreds of python packages because they miss a dependency, and regular (free) testing on Power makes those problems much easier to catch.

**Comment by joachimmetz** [comment]
@gerrith3 it could have helped to provide this context first as an issue and @sanjay-cpu being more explanatory.

1. for this project the Travis configuration is generated using l2tdevtools, this will address most of the the other log2timeline projects as weel
2. IMHO 1x ppc64le test for Ubuntu would suffice to meet these test requirements

**Comment by gerrith3** [comment]
@joachimmetz apologies for the lack of context.  We'll take this feedback and see if we can generate a more concrete template for the teams helping with these conversions to use as we continue to update all travis builds.  I would agree on 1x for Ubuntu on Power to meet requirements.  @sanjay-cpu can you look up the log2timeline/l2tdevtools and see if you can update that as requested?  And @joachimmetz can you clarify where the GIFT PPA is and how we update it?  That's one that I'm not familiar with.

**Comment by joachimmetz** [comment]
> @joachimmetz can you clarify where the GIFT PPA is and how we update it? 

The GIFT PPA is https://launchpad.net/~gift but I would recommend that we (as maintainers) do this instead, since access is required. The same for updating the templates, since a certain alignment of steps is required.

I've created https://github.com/log2timeline/l2tdevtools/issues/915 to track this.

> We'll take this feedback and see if we can generate a more concrete template for the teams helping with these conversions to use as we continue to update all travis builds.

Maybe having 1 base issue to reference to could be useful as well

**Comment by sanjay-cpu** [comment]
Sure @gerrith3 , i will check it.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfdatetime/pull/173 should suffice as a replacement. COPR does not appear to have a ppc64le architecture support so no need to add ppc64le that cover the Fedora tests.

**Comment by gerrith3** [comment]
We also do not currently have fedora in travis-ci, so wouldn't be able to cover that.  It is a desire of ours to get there but we haven't had a lot of motivation for it as yet, and still fleshing out a few minor differences in the ubuntu base images for ppc64le.  However, if it makes sense we can add a travis build on Ubuntu there for now, if you think that would have value here.

**Comment by joachimmetz** [comment]
> However, if it makes sense we can add a travis build on Ubuntu there for now

Not sure if I'm following you, but I think has been completed in https://github.com/log2timeline/dfdatetime/pull/173

**Comment by gerrith3** [comment]
@joachimmetz yep - that's good.  Probably the part where I lost you is that we do want to have fedora as a test base in Travis CI but we haven't had a chance to add that capability yet.  In time, for those who want to do regression tests with fedora, we should have that ability.  Probably just more of an FYI at this point, though.  Thanks for all the help here!!

**Pull request closed without merging**
